config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'portfolios#index'

  resources :portfolios, only: [:index, :show, :new, :create, :destroy] do
    resources :positions
  end

  resources :stocks

end

app/models/markit.rb
require 'httparty'
require 'pp'

class Markit
  include HTTParty
  base_uri 'http://dev.markitondemand.com/Api/v2/Quote'

  def initialize(term)
    @options = { query: {symbol: term}}
  end

  def quote
    self.class.get("", @options)
  end
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  has_many :positions, dependent: :destroy
  has_many :stocks, :through => :positions

  def available_cash
    tradeable_cash = cash
    self.positions.each do |position|
      tradeable_cash = tradeable_cash - position.value
    end
    tradeable_cash
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :portfolio
  belongs_to :stock

  def value
    quantity * open_price
  end

  def current_value
    quantity * stock.current_price
  end

  def profit_loss
    short ? -(current_value - value) : current_value - value
  end
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_many :positions, dependent: :destroy
  has_many :portfolios, :through => :positions

  def current_price
    previous_day = DateTime.now - 1
    if updated_at > previous_day
      return price
    else
      new_price = Markit.new(self.ticker_symbol).quote['StockQuote']['LastPrice'].to_i
      self.price = new_price
      self.save
      return price
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :authenticate_user!

  def index
    @portfolios = Portfolio.all
  end

  def show
    find_models
    @positions = Position.where(portfolio_id: params[:id])
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    Portfolio.create(portfolio_params)
    redirect_to portfolios_url
  end

  def destroy
    find_models
    @portfolio.destroy
    redirect_to portfolios_url
  end

  private

  def portfolio_params #scary internet people
    params.require(:portfolio).permit(:title, :cash)
  end

  def find_models
    @portfolio = Portfolio.find(params[:id])
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def index
    @positions = Position.all
  end

  def new
    find_models
    @position = Position.new
  end

  def create
    find_models
    @position = Position.new(position_params)
    @position.portfolio = @portfolio
    @position.save
    redirect_to portfolio_url(params[:portfolio_id])
  end

  private

  def find_models
    @portfolio = Portfolio.find(params[:portfolio_id])
  end

  def position_params
    params.require(:position).permit(:short, :open_price, :close_price, :current_price, :quantity, :stock_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def index
    @stocks = Stock.all
  end

  def new
    @stock = Stock.new
  end

  def create
    Stock.create(stock_params)
    redirect_to stocks_url
  end

  def edit
    find_models
  end

  def update
    find_models
    @stock.update_attributes(stock_params)
    redirect_to stocks_url
  end

  private

  def find_models
    @stock = Stock.find(params[:id])
  end

  def stock_params #scary internet people
    params.require(:stock).permit(:ticker_symbol, :company_name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wsot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/portfolios/index.html.erb
<h2>WSOT</h2>

<ul>
  <% @portfolios.each do |portfolio| %>
    <li>
      <%=link_to portfolio.title, portfolio_url(portfolio.id) %> <%= link_to 'delete', "/portfolios/#{portfolio.id}", data: {confirm: 'Are you sure?'}, method: :delete %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Portfolio', new_portfolio_path %>

<%= link_to 'Tradeable Securities', stocks_path %>

<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>

app/views/portfolios/new.html.erb
<h3>
  A PORTFOLIO FORM GOES HERE!
</h3>

<h3>
  YOU SPECIFY YOUR PORTFOLIO SPECIFICATIONS
</h3>

<%= form_for(@portfolio) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :starting_cash %>
  <%= f.text_field :cash %>

  <%= f.submit %>
<% end %>

<%= link_to 'Back to Portfolios', portfolios_path %>

app/views/portfolios/show.html.erb
<h2><%= @portfolio.title %></h2>

<h3>
  Cash Available for Trading: $<%= @portfolio.available_cash %>
</h3>

<table>
  <tr>
    <td> Symbol </td>
    <td> Quantity </td>
    <td> Cost </td>
    <td> Market Value </td>
    <td> Gain </td>
  </tr>
  <% @positions.each do |position| %>
    <tr>
      <td><%= position.short ? 'SHORT' : 'LONG' %> - <%= position.stock.ticker_symbol %></td>
      <td><%= position.quantity %></td>
      <td>$<%= position.value %></td>
      <td>$<%= position.current_value %></td>
      <td>$<%= position.profit_loss %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Back to Portfolios', portfolios_path %>

<% if @portfolio.available_cash < 100 %>
<% else %>
  <%= link_to 'New Position', new_portfolio_position_path(portfolio_id: params[:id]) %>
<% end %>

app/views/positions/new.html.erb
<h1>
  CREATE NEW POSITION HERE
</h1>

<ul>
  <%= form_for [@portfolio, @position] do |f| %>
    <li>
      <%= f.label :short? %>
      <%= f.check_box :short %>
    </li>

    <li>
      <%= f.label :open_price %>
      <%= f.text_field :open_price %>
    </li>

    <li>
      <%= f.label :quantity %>
      <%= f.text_field :quantity %>
    </li>

    <li>
      <%= f.label :stock %>
      <%= f.collection_select :stock_id, Stock.all, :id, :ticker_symbol %>
    </li>

    <li>
      <%= f.submit %>
    </li>
  <%end%>
</ul>

<%= link_to 'Back to Portfolio', portfolio_path(id: params[:portfolio_id]) %>

app/views/stocks/edit.html.erb
<h3>Edit Stock Form</h3>

<%= form_for @stock do |f| %>

  <%= f.label :ticker_symbol %>
  <%= f.text_field :ticker_symbol %>

  <%= f.label :company_name %>
  <%= f.text_field :company_name %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>

app/views/stocks/index.html.erb
<h3>
  LIST OF TRADEABLE SECURITIES
</h3>

<ul>
  <% @stocks.each do |stock| %>
    <li>
      <%= link_to stock.ticker_symbol, edit_stock_path(stock.id) %> - Price <%= stock.price %>
    </li>
  <% end %>
</ul>


<%= link_to 'Home', portfolios_path %>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h3>New Stock Form</h3>

<%= form_for @stock do |f| %>

  <%= f.label :ticker_symbol %>
  <%= f.text_field :ticker_symbol %>

  <%= f.label :company_name %>
  <%= f.text_field :company_name %>

  <%= f.label :price %>
  <%= f.text_field :price %>

  <%= f.submit %>
<% end %>